# Generated by Django 6.0.5 on 2026-05-30 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_turno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='contraseña',
            new_name='contrasena',
        ),
        migrations.RenameField(
            model_name='profesional',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
