# Generated by Django 6.0.5 on 2026-05-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_rename_contraseña_paciente_contrasena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
